# Generated by Django 4.2.7 on 2026-08-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'verbose_name': 'Auditoría', 'verbose_name_plural': 'Auditorías'},
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='objeto_id',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
