# Generated by Django 4.2.7 on 2026-08-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('cuit', models.CharField(help_text='CUIT sin guiones', max_length=11)),
                ('condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributo'), ('EXENTO', 'Exento')], max_length=10)),
                ('inicio_actividades', models.DateField()),
                ('iibb', models.CharField(max_length=50, verbose_name='Ingresos Brutos')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('modo_arica_homologacion', models.BooleanField(default=True, help_text='Tildado = Pruebas (Homologación), Destildado = Producción')),
                ('punto_de_venta', models.IntegerField(default=1, help_text='Número de Punto de Venta habilitado en ARCA')),
                ('certificado_crt', models.FileField(blank=True, null=True, upload_to='arca/certs/')),
                ('clave_privada_key', models.FileField(blank=True, null=True, upload_to='arca/keys/')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
