# Generated by Django 4.2.7 on 2026-08-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default='Mi Comercio S.A.', max_length=200)),
                ('nombre_fantasia', models.CharField(blank=True, default='Mi Negocio', max_length=200, null=True)),
                ('cuit', models.CharField(default='20-12345678-9', max_length=20)),
                ('condicion_iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MO', 'Monotributo'), ('EX', 'Exento')], default='MO', max_length=5)),
                ('iibb', models.CharField(blank=True, help_text='Número de Ingresos Brutos', max_length=50, null=True)),
                ('inicio_actividades', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, default='Av. Principal 123', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('punto_de_venta', models.IntegerField(default=1, help_text='Número de Punto de Venta habilitado en ARCA (Ej: 1)')),
                ('ambiente_arca', models.CharField(choices=[('HOMO', 'Homologación (Pruebas)'), ('PROD', 'Producción (Real)')], default='HOMO', max_length=5)),
                ('certificado_crt', models.FileField(blank=True, help_text='Archivo .crt obtenido en ARCA', null=True, upload_to='certificados/')),
                ('clave_privada_key', models.FileField(blank=True, help_text='Archivo .key de la clave privada', null=True, upload_to='certificados/')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
        migrations.DeleteModel(
            name='EmpresaConfiguracion',
        ),
    ]
