# Generated by Django 4.2.7 on 2026-08-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_empresaconfig_delete_empresaconfiguracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='email_smtp_host',
            field=models.CharField(default='smtp.gmail.com', help_text='Ej: smtp.gmail.com o smtp.office365.com', max_length=150),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='email_smtp_password',
            field=models.CharField(blank=True, help_text='Contraseña de aplicación', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='email_smtp_port',
            field=models.IntegerField(default=587, help_text='Puerto SMTP habitual: 587 (TLS) o 465 (SSL)'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='email_smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='email_smtp_user',
            field=models.CharField(blank=True, help_text='Tu correo emisor', max_length=150, null=True),
        ),
    ]
