# Generated by Django 4.2.7 on 2026-08-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_empresaconfig_email_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo del Comercio'),
        ),
    ]
