# Generated by Django 5.2.17 on 2026-08-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permisos_temporales',
            field=models.ManyToManyField(related_name='usuarios_temporales', through='usuarios.PermisoTemporal', through_fields=('usuario', 'permission'), to='auth.permission'),
        ),
    ]
