# Generated by Django 4.2.7 on 2026-08-18 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_o_razon_social', models.CharField(max_length=200)),
                ('tipo_documento', models.IntegerField(choices=[(80, 'CUIT'), (96, 'DNI'), (99, 'Sin Identificar (Consumidor Final)')], default=96)),
                ('numero_documento', models.CharField(default='0', max_length=11)),
                ('condicion_iva', models.CharField(choices=[('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('MONO', 'Monotributista'), ('EX', 'Exento')], default='CF', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Débito/Crédito'), ('transferencia', 'Transferencia / MP'), ('cuenta_corriente', 'Cuenta Corriente')], default='efectivo', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo_comprobante', models.IntegerField(choices=[(1, 'Factura A'), (6, 'Factura B'), (11, 'Factura C'), (3, 'Nota de Crédito A'), (8, 'Nota de Crédito B'), (13, 'Nota de Crédito C'), (0, 'Ticket No Fiscal')], default=0)),
                ('punto_de_venta', models.IntegerField(blank=True, null=True)),
                ('numero_comprobante', models.BigIntegerField(blank=True, null=True)),
                ('cae', models.CharField(blank=True, max_length=14, null=True, verbose_name='CAE')),
                ('cae_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento CAE')),
                ('estado_arca', models.CharField(choices=[('PENDIENTE', 'Pendiente de Enviar'), ('APROBADO', 'Aprobado por ARCA'), ('RECHAZADO', 'Rechazado por ARCA'), ('NO_REQUERIDO', 'Comprobante Interno / Sin Facturar')], default='PENDIENTE', max_length=15)),
                ('error_arca', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alicuota_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
