# Generated by Django 4.2.7 on 2026-08-18 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='total_iva',
            new_name='monto_iva',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_o_razon_social',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cae_vencimiento',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='error_arca',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado_arca',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='punto_de_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tipo_comprobante',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='Consumidor Final', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='vencimiento_cae',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condicion_iva',
            field=models.CharField(choices=[('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('MO', 'Monotributo'), ('EX', 'Exento')], default='CF', max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT'), ('PAS', 'Pasaporte')], default='DNI', max_length=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='alicuota_iva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cae',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TRANSFERENCIA', 'Transferencia / Mercado Pago')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
    ]
