# Generated by Django 4.2.7 on 2026-08-19 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_proveedor_alter_movimientostock_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0002_alter_detalleventa_options_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='condicion_iva',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='alicuota_iva',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cae',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='monto_iva',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='numero_comprobante',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vencimiento_cae',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI / CUIT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CajaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fondo Inicial ($)')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('monto_final_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Efectivo Real Contado ($)')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diferencia ($)')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Notas')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cajaturno'),
        ),
    ]
