# Generated by Django 5.2.17 on 2026-08-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cae',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CAE Autorizado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_comprobante',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Comprobante ARCA'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_comprobante',
            field=models.IntegerField(choices=[(6, 'Factura B'), (1, 'Factura A'), (11, 'Factura C'), (0, 'Ticket No Fiscal')], default=6, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AddField(
            model_name='venta',
            name='vencimiento_cae',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento CAE'),
        ),
    ]
