# Generated by Django 4.2.7 on 2026-08-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_cae_venta_numero_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Recibido'),
        ),
        migrations.AddField(
            model_name='venta',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Vuelto'),
        ),
    ]
